# Generated by Django 4.0.5 on 2022-11-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default=None, max_length=50)),
                ('price', models.BigIntegerField(default=None)),
                ('sdesc', models.TextField(default=None)),
                ('ldesc', models.TextField(default=None)),
                ('file_name', models.FileField(default=None, max_length=255, upload_to='')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
                ('subcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
